default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: insta_app_development

test:
  <<: *default
  database: insta_app_test

production:
  <<: *default
  database: insta_app_production
  username: insta_app
  password: <%= ENV['INSTA_APP_DATABASE_PASSWORD'] %>
